name:                asl
version:             0.1.0.0
github:              "githubuser/asl"
license:             BSD-3-Clause
author:              "Juan Bautista Figueredo"
maintainer:          "juan.b.figueredo01@gmail.com"
copyright:           "2024 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/asl#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- directory
- array
- transformers
- gloss 
- ansi-terminal >= 0.11 && <0.12
- pretty >= 1.1 && < 1.2


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2 
default-extensions:
- TupleSections
- MultiWayIf
- LambdaCase
- DataKinds
- PolyKinds
- FlexibleInstances
- FlexibleContexts
- StandaloneDeriving
- GADTs

library:
  source-dirs: src

executables:
  asl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - asl
    - base >= 4.7 && < 5
    - gloss
    - OpenGLRaw
    - directory
    build-tools-depends:
    - happy

#tests:
#  asl-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - asl
